# This is a Dropwizard-based Microservice
# See https://dropwizard.github.io/dropwizard/manual/configuration.html

# Group Id to publish artifacts to
groupId: org.nodejs.dist

# Artifact Id to publish NodeJS binaries
nodeJsArtifactId: nodejs-binaries

# Artifact Id to publish NPM binaries
npmArtifactId: npm-binaries

# Root URL to download NodeJS binaries from
nodeJsBinariesRootUrl: "https://nodejs.org/dist"

# Url parts to download the different artifacts
nodeJsBinariesUrl: "/v${version}/node-v${version}-${os}-${arch}.${type}"
nodeJsBinariesUrlWindows: "/v${version}/win-${arch}/node.${type}"
nodeJsBinariesUrlWindowsX86Legacy: "/v${version}/node.${type}"
nodeJsBinariesUrlWindowsX64Legacy: "/v${version}/${arch}/node.${type}"
npmBinariesUrl: "/npm/npm-${version}.${type}"

# SHA-256 checksums file
nodeJsChecksumUrl: "/v${version}/SHASUMS256.txt"

# Sample versions for index page
nodeJsSampleVersion: 4.4.0
npmSampleVersion: 1.4.9

# HTTP Client settings
httpClient:
  connectionTimeout: 2s
  timeout: 5s
  timeToLive: 1h
  cookiesEnabled: false
  retries: 2
  userAgent: Maven NodeJS Proxy

# Jetty configuration
server:
  # Disable gzip compression to avoid corruption of tar.gz files
  gzip:
    enabled: false

# Logging configuration
logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: target/logs/maven-nodejs-proxy.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: target/logs/maven-nodejs-proxy-%d.log
      archivedFileCount: 5
